"""Flask application: routes + security middleware.

Security posture (mirrors todoist-points; see repo CLAUDE.md):

- App-level shared-password gate when APP_PASSWORD is set: every request that
  isn't /login, /logout, a static asset or /healthz is redirected to /login
  until the visitor presents the one shared password. Success stores a signed
  session marker (SESSION_SECRET); the raw password is never stored or logged.
  Unset APP_PASSWORD = gate OFF (unchanged behavior) — so it can ship dormant
  behind Cloudflare Access and be switched on at cutover. See password_gate.py.
- Cloudflare Access JWT verified in-app when CF_ACCESS_AUD +
  CF_ACCESS_TEAM_DOMAIN are set (fail closed); unset = local dev mode. Kept
  intact and env-gated — it just won't be configured after cutover.
- APP_HOST, when set, pins the Host (all requests) and Origin (POSTs)
  headers — CSRF/rebinding defense for state-changing routes incl. POST /login.
- HTTPS is enforced at the origin as well as at the Cloudflare edge: a request
  whose X-Forwarded-Proto (trimmed, case-folded) is exactly "http" is 307'd to
  https://<APP_HOST> with Cache-Control: no-store + Vary: X-Forwarded-Proto,
  and every response carries Strict-Transport-Security. See _force_https.
- The only user input is a Letterboxd username: validated with
  scraper.is_valid_name before it is used anywhere, and passed through
  util.safe_filename before touching the filesystem. No other part of a
  URL or form ever reaches a path or an outbound request.
- Jinja autoescape is on (Flask default for .html); nothing remote-derived
  is ever marked |safe. Reports are static HTML generated by report.py's
  escaping renderers.
"""

from __future__ import annotations

import hmac
import logging
import os
import re
import secrets
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import quote, urlsplit

from flask import (Flask, Response, abort, g, redirect, render_template,
                   request, send_file, session, url_for)

from ..report import METHODOLOGY
from ..scraper import is_valid_name
from ..util import safe_filename
from .auth import AccessAuthError, AccessVerifier
from .jobs import MAX_USERNAME_LEN, JobManager
from .password_gate import LoginRateLimiter, client_ip, safe_next

log = logging.getLogger("tastetwin.web")

_CSP = ("default-src 'self'; style-src 'self' 'unsafe-inline'; "
        "img-src 'self' data:; form-action 'self'; frame-ancestors 'none'; "
        "base-uri 'none'; object-src 'none'")

# HSTS: one year, deliberately WITHOUT includeSubDomains and WITHOUT preload —
# each host owns its own policy (matches the apex landing page's
# snippets/security-headers.conf, the reference implementation).
_HSTS = "max-age=31536000"

# APP_HOST is operator-configured, but the http->https redirect splices it into
# a Location header, so it is validated as a bare hostname (no scheme, no port,
# no path, no credentials) before it can be used there.
# NOTE \A/\Z, not ^/$: "$" also matches before a TRAILING NEWLINE, so
# "evil.net\n" would pass a "^...$" check and reach a response header.
# Per-LABEL pattern (each dot-separated label 1-63 chars, no leading or
# trailing hyphen) — byte-identical to the one in jjho-fan-almanac, so all
# five sibling apps agree on exactly what a hostname is.
_HOSTNAME_RE = re.compile(
    r"\A(?=.{1,253}\Z)[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?"
    r"(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)*\Z")

# A raw request target we are willing to echo back verbatim into a Location
# header: origin-form (starts with "/") and printable ASCII only. Anything else
# (CR/LF, NUL, spaces, raw UTF-8, absolute-form URIs, "*") is re-encoded from
# the parsed request instead of being trusted.
_SAFE_TARGET_RE = re.compile(r"\A/[\x21-\x7e]*\Z")  # \Z: see above

# View-only message shown when a POST /run is refused in viewer mode.
VIEWER_ONLY_MESSAGE = (
    "This site is view-only — new taste-twin reports are generated on request. "
    "Browse the existing reports below.")


def _env_truthy(name: str) -> bool:
    return os.environ.get(name, "").strip().lower() in ("1", "true", "yes", "on")


def _request_target() -> str:
    """Path + query to append to the https redirect, preserving encoding.

    This must round-trip percent-encoding byte-for-byte, and Flask's
    ``request.path`` is already URL-DECODED: building the target from it turns
    ``/a%20b`` into ``/a b`` and ``/a%2Fb`` into ``/a/b`` — a *different*
    resource. The WSGI layer keeps the original request-target bytes in
    ``RAW_URI`` / ``REQUEST_URI`` (gunicorn, the Werkzeug dev server and the
    Flask test client all set them), so prefer those verbatim.

    The fallback (no raw target in the environ) re-encodes the decoded path and
    re-attaches the raw query string; it is lossy for ``%2F`` but never unsafe,
    and anything that still doesn't look like a clean origin-form target
    degrades to ``/`` rather than reaching a response header.
    """
    for key in ("RAW_URI", "REQUEST_URI"):
        raw = request.environ.get(key)
        if isinstance(raw, str) and _SAFE_TARGET_RE.match(raw):
            return raw
    target = quote(request.path, safe="/-._~!$&'()*+,;=:@")
    qs = request.query_string.decode("latin-1")
    if qs:
        target = f"{target}?{qs}"
    return target if _SAFE_TARGET_RE.match(target) else "/"


def create_app(data_dir: str | Path | None = None, runner=None,
               start_worker: bool = True) -> Flask:
    """App factory. `runner`/`start_worker` exist for tests.

    Viewer mode (env ``TASTE_TWIN_VIEWER_MODE`` truthy) turns the app into a
    read-only report gallery: the homepage hides the username form, ``POST
    /run`` refuses to enqueue, and no background worker / dataset ingest runs.
    This is how the deployed box instance runs — Letterboxd's Cloudflare bot
    management challenges the box's server IP, so live scraping happens on a
    residential IP (Graham's Mac) and reports are synced to the box (see
    ``scripts/publish.py``). Default OFF: full-mode behavior is unchanged.
    """
    if not logging.getLogger().handlers:
        logging.basicConfig(level=logging.INFO,
                            format="%(asctime)s %(levelname)s %(message)s",
                            datefmt="%H:%M:%S")

    app = Flask(__name__)
    data_dir = Path(
        data_dir or os.environ.get("TASTETWIN_DATA", "data")).resolve()

    aud = os.environ.get("CF_ACCESS_AUD", "")
    team_domain = os.environ.get("CF_ACCESS_TEAM_DOMAIN", "")
    app_host = os.environ.get("APP_HOST", "")
    verifier: AccessVerifier | None = None
    if aud and team_domain:
        verifier = AccessVerifier(aud, team_domain)
        log.info("Cloudflare Access verification ENABLED (team %s)",
                 team_domain)
    else:
        log.warning("CF_ACCESS_AUD / CF_ACCESS_TEAM_DOMAIN not set — "
                    "running UNAUTHENTICATED (local dev mode only; never "
                    "expose this).")
    if not app_host:
        log.warning("APP_HOST not set — Host/Origin pinning disabled "
                    "(local dev mode only).")

    viewer_mode = _env_truthy("TASTE_TWIN_VIEWER_MODE")
    if viewer_mode:
        log.info("TASTE_TWIN_VIEWER_MODE enabled — read-only gallery: no "
                 "username form, POST /run refused, no worker/ingest started.")

    # -- app-level shared-password gate (env-gated by APP_PASSWORD) -----------
    app_password = os.environ.get("APP_PASSWORD", "")
    password_gate_enabled = bool(app_password)
    # Sign the session cookie: prefer SESSION_SECRET, reuse SECRET_KEY if
    # present, else fall back to an ephemeral key (a warning is logged when the
    # gate is on, since sessions then won't survive a restart). Never hardcode.
    session_secret = (os.environ.get("SESSION_SECRET", "")
                      or os.environ.get("SECRET_KEY", ""))
    app.secret_key = session_secret or secrets.token_hex(32)
    app.config.update(
        SESSION_COOKIE_HTTPONLY=True,
        SESSION_COOKIE_SECURE=True,
        SESSION_COOKIE_SAMESITE="Lax",
        PERMANENT_SESSION_LIFETIME=timedelta(days=30),
    )
    login_limiter = LoginRateLimiter()
    if password_gate_enabled:
        if not session_secret:
            log.warning("APP_PASSWORD set but SESSION_SECRET/SECRET_KEY unset "
                        "— using an ephemeral signing key; sessions won't "
                        "survive a restart. Set SESSION_SECRET.")
        log.info("APP_PASSWORD set — shared-password gate ENABLED.")
    else:
        log.info("APP_PASSWORD unset — shared-password gate OFF "
                 "(app behaves as before).")
    # Paths reachable without a session even when the gate is on.
    gate_exempt_paths = {"/login", "/logout", "/healthz"}

    manager = JobManager(data_dir, runner=runner)
    manager.recover()
    # In viewer mode nothing is ever enqueued, so we never start the worker
    # thread — that also means the ~600MB dataset ingest is never triggered
    # and the app boots cleanly even if pool.db is absent.
    if start_worker and not viewer_mode:
        manager.start()
    app.extensions["tastetwin_jobs"] = manager

    @app.context_processor
    def _inject_viewer_mode():
        return {"viewer_mode": viewer_mode}

    @app.template_filter("datetime")
    def _fmt_datetime(ts) -> str:
        try:
            return datetime.fromtimestamp(float(ts)).strftime("%Y-%m-%d %H:%M")
        except (TypeError, ValueError, OSError, OverflowError):
            return "—"

    # -- middleware -----------------------------------------------------------

    # APP_HOST doubles as the redirect target for the http->https upgrade, so
    # it has to be a bare hostname before it can be spliced into a Location.
    https_host = app_host if _HOSTNAME_RE.match(app_host or "") else ""
    if app_host and not https_host:
        log.warning("APP_HOST=%r is not a bare hostname — the http->https "
                    "redirect is DISABLED (Host pinning is unaffected).",
                    app_host)
    elif not https_host:
        log.warning("APP_HOST not set — http->https redirect disabled "
                    "(local dev / CLI). HSTS is still sent.")

    @app.before_request
    def _force_https():
        """Upgrade plain-http visitors to https (defence in depth).

        Registered FIRST so it runs ahead of the password gate, the CF-Access
        check and the Host pin: a plain-http visitor is redirected before any
        credential is read off the wire.

        Only the Cloudflare tunnel reaches this container, and cloudflared
        forwards the visitor's scheme as X-Forwarded-Proto. Redirect ONLY when
        that header, trimmed and case-folded, is exactly "http":

        - An ABSENT header means the request did not arrive through the tunnel
          — the compose healthcheck (``urlopen('http://127.0.0.1:8080/
          healthz')``), local dev, and the test suite. Those must NOT be
          redirected. The header rule IS the exemption, so no route needs one.
        - URI schemes are case-INSENSITIVE (RFC 3986 §3.1, RFC 9110), so the
          comparison is ``.strip().lower()``. A case-sensitive ``!= "http"``
          fails in the dangerous direction: ``X-Forwarded-Proto: HTTP`` would
          be served 200 over plain http. A multi-hop value ("http, https")
          still does NOT match — we only act on an unambiguous single scheme.
        - The target is always built from the configured APP_HOST, NEVER from
          the request's own Host/URL: reflecting an attacker-supplied Host
          would turn this into an open redirect.
        - With APP_HOST unset (or malformed) there is no safe target to name,
          so we fail OPEN — no redirect — rather than guess. That keeps local
          dev, the CLI path and the tests working.

        307, not 301: the emitted Location is byte-identical to the requested
        URL, and a 301 with no freshness information is heuristically cacheable
        *indefinitely* (RFC 9111 §4.2.2). If the edge's "Always Use HTTPS" ever
        regressed, a shared cache could store this self-referential redirect —
        under ``/static/*.css|.js``, exactly what Cloudflare caches by default
        — and then serve it to https visitors: broken assets, or a loop. A
        misconfigured APP_HOST under a 301 would likewise be sticky in every
        visitor's browser with no way to recall it. 307 also preserves the
        method, so a plain-http POST is re-sent over https rather than being
        silently downgraded to a bodiless GET. HSTS already provides the
        durable client-side upgrade, so permanence buys nothing here.
        ``Cache-Control: no-store`` + ``Vary: X-Forwarded-Proto`` say out loud
        what the response actually depends on.
        """
        if not https_host:
            return None
        proto = (request.headers.get("X-Forwarded-Proto") or "").strip().lower()
        if proto != "http":
            return None
        resp = redirect(f"https://{https_host}{_request_target()}", code=307)
        resp.headers["Cache-Control"] = "no-store"
        resp.headers["Vary"] = "X-Forwarded-Proto"
        return resp

    @app.before_request
    def _password_gate():  # redirects unauth users to /login
        if not password_gate_enabled:
            return None
        path = request.path
        if path in gate_exempt_paths:
            return None
        if (request.endpoint == "static"
                or path.startswith(app.static_url_path.rstrip("/") + "/")):
            return None
        if session.get("tt_authed") is True:
            return None
        nxt = path
        if request.query_string:
            nxt = f"{path}?{request.query_string.decode('latin-1')}"
        return redirect(url_for("login", next=nxt))

    @app.before_request
    def _cloudflare_access():  # fail closed on every route but /healthz
        if verifier is None or request.path == "/healthz":
            return None
        token = (request.headers.get("Cf-Access-Jwt-Assertion")
                 or request.cookies.get("CF_Authorization", ""))
        try:
            g.access_claims = verifier.verify(token)
        except AccessAuthError as exc:
            log.warning("rejected request to %s: %s", request.path, exc)
            abort(403)
        return None

    @app.before_request
    def _host_origin_pin():
        if not app_host or request.path == "/healthz":
            return None
        if request.host.split(":", 1)[0].lower() != app_host:
            abort(403)
        if request.method == "POST":
            # CSRF defense: a state-changing POST must carry at least one
            # same-origin signal that matches app_host. Origin is the most
            # trustworthy — if present it alone must match. When Origin is
            # absent (some browsers omit it) fall back to a same-host
            # Referer. A POST carrying NEITHER cannot be proven same-origin,
            # so it is rejected.
            origin = request.headers.get("Origin", "")
            referer = request.headers.get("Referer", "")
            if origin:
                if (urlsplit(origin).hostname or "").lower() != app_host:
                    abort(403)
            elif referer:
                if (urlsplit(referer).hostname or "").lower() != app_host:
                    abort(403)
            else:
                abort(403)
        return None

    @app.after_request
    def _security_headers(resp: Response) -> Response:
        resp.headers.setdefault("X-Content-Type-Options", "nosniff")
        resp.headers.setdefault("X-Frame-Options", "DENY")
        # "same-origin" (not "no-referrer") is required for the CSRF pin to work:
        # under "no-referrer" a browser sends `Origin: null` AND no Referer on the
        # app's own same-origin form POST, which _host_origin_pin then rejects (403).
        # "same-origin" makes same-origin POSTs carry the real Origin (CSRF stays
        # enforced) while still sending NO referrer to cross-origin links (e.g.
        # outbound letterboxd.com URLs in reports) — preserving the privacy intent.
        resp.headers.setdefault("Referrer-Policy", "same-origin")
        resp.headers.setdefault("Content-Security-Policy", _CSP)
        # HSTS: tell browsers to stick to https for a year. No
        # includeSubDomains / preload — each host owns its own policy.
        resp.headers.setdefault("Strict-Transport-Security", _HSTS)
        return resp

    # -- routes -----------------------------------------------------------------

    @app.get("/healthz")
    def healthz():
        return {"status": "ok"}

    @app.get("/login")
    def login():
        if not password_gate_enabled:
            return redirect(url_for("index"))
        if session.get("tt_authed") is True:
            return redirect(safe_next(request.args.get("next")))
        return render_template(
            "login.html", next=request.args.get("next", ""), error=None)

    @app.post("/login")
    def login_post():
        # Host/Origin CSRF pin already ran in before_request for this POST.
        if not password_gate_enabled:
            return redirect(url_for("index"))
        next_target = request.form.get("next", "")
        ip = client_ip()
        if login_limiter.is_blocked(ip):
            log.warning("login blocked (rate limit) for %s", ip)
            return render_template(
                "login.html", next=next_target,
                error="Too many failed attempts. Try again in a few minutes."
            ), 429
        supplied = request.form.get("password", "")
        if hmac.compare_digest(supplied, app_password):
            session.clear()
            session["tt_authed"] = True
            session.permanent = True
            login_limiter.reset(ip)
            return redirect(safe_next(next_target))
        login_limiter.record_failure(ip)
        log.warning("failed login attempt from %s", ip)  # never log the password
        return render_template(
            "login.html", next=next_target,
            error="Incorrect password."), 401

    @app.get("/logout")
    def logout():
        session.clear()
        if password_gate_enabled:
            return redirect(url_for("login"))
        return redirect(url_for("index"))

    @app.get("/")
    def index():
        return render_template("index.html", runs=manager.list_runs(),
                               pool_state=manager.pool_state,
                               max_len=MAX_USERNAME_LEN)

    @app.post("/run")
    def start_run():
        # Auth + Host/CSRF pin already ran in before_request. In viewer mode we
        # refuse to enqueue (no live jobs on the box) but still render the
        # gallery so the visitor lands somewhere useful.
        if viewer_mode:
            return render_template("index.html", runs=manager.list_runs(),
                                   pool_state=manager.pool_state,
                                   max_len=MAX_USERNAME_LEN,
                                   error=VIEWER_ONLY_MESSAGE), 403
        job, error = manager.enqueue(request.form.get("username", ""))
        if job is None:
            return render_template("index.html", runs=manager.list_runs(),
                                   pool_state=manager.pool_state,
                                   max_len=MAX_USERNAME_LEN,
                                   error=error), 400
        return redirect(url_for("run_status", username=job.username))

    @app.get("/run/<username>")
    def run_status(username: str):
        if not is_valid_name(username) or len(username) > MAX_USERNAME_LEN:
            abort(404)
        key = safe_filename(username.lower())
        job = manager.get(key)
        report_exists = (
            data_dir / "runs" / key / "report.html").exists()
        if job is None and not report_exists:
            abort(404)
        return render_template(
            "status.html", job=job, username=username,
            position=manager.position(key),
            log_lines=manager.log_tail(key),
            report_exists=report_exists,
            pool_state=manager.pool_state,
            refresh=job is not None and job.status in ("queued", "running"))

    @app.get("/report/<username>")
    def report(username: str):
        if not is_valid_name(username) or len(username) > MAX_USERNAME_LEN:
            abort(404)
        runs_root = (data_dir / "runs").resolve()
        path = (runs_root / safe_filename(username.lower())
                / "report.html").resolve()
        # is_valid_name + safe_filename already forbid traversal; this
        # containment check is belt-and-braces.
        if not path.is_relative_to(runs_root) or not path.is_file():
            abort(404)
        resp = send_file(path, mimetype="text/html")
        resp.headers["Content-Disposition"] = "inline"
        return resp

    @app.get("/about")
    def about():
        return render_template("about.html", methodology=METHODOLOGY)

    return app
