"""Flask application: routes + security middleware.

Security posture (mirrors todoist-points; see repo CLAUDE.md):

- Cloudflare Access JWT verified in-app when CF_ACCESS_AUD +
  CF_ACCESS_TEAM_DOMAIN are set (fail closed); unset = local dev mode.
- APP_HOST, when set, pins the Host (all requests) and Origin (POSTs)
  headers — CSRF/rebinding defense for the single state-changing route.
- The only user input is a Letterboxd username: validated with
  scraper.is_valid_name before it is used anywhere, and passed through
  util.safe_filename before touching the filesystem. No other part of a
  URL or form ever reaches a path or an outbound request.
- Jinja autoescape is on (Flask default for .html); nothing remote-derived
  is ever marked |safe. Reports are static HTML generated by report.py's
  escaping renderers.
"""

from __future__ import annotations

import logging
import os
from datetime import datetime
from pathlib import Path
from urllib.parse import urlsplit

from flask import (Flask, Response, abort, g, redirect, render_template,
                   request, send_file, url_for)

from ..report import METHODOLOGY
from ..scraper import is_valid_name
from ..util import safe_filename
from .auth import AccessAuthError, AccessVerifier
from .jobs import MAX_USERNAME_LEN, JobManager

log = logging.getLogger("tastetwin.web")

_CSP = ("default-src 'self'; style-src 'self' 'unsafe-inline'; "
        "img-src 'self' data:; form-action 'self'; frame-ancestors 'none'")


def create_app(data_dir: str | Path | None = None, runner=None,
               start_worker: bool = True) -> Flask:
    """App factory. `runner`/`start_worker` exist for tests."""
    if not logging.getLogger().handlers:
        logging.basicConfig(level=logging.INFO,
                            format="%(asctime)s %(levelname)s %(message)s",
                            datefmt="%H:%M:%S")

    app = Flask(__name__)
    data_dir = Path(
        data_dir or os.environ.get("TASTETWIN_DATA", "data")).resolve()

    aud = os.environ.get("CF_ACCESS_AUD", "")
    team_domain = os.environ.get("CF_ACCESS_TEAM_DOMAIN", "")
    app_host = os.environ.get("APP_HOST", "")
    verifier: AccessVerifier | None = None
    if aud and team_domain:
        verifier = AccessVerifier(aud, team_domain)
        log.info("Cloudflare Access verification ENABLED (team %s)",
                 team_domain)
    else:
        log.warning("CF_ACCESS_AUD / CF_ACCESS_TEAM_DOMAIN not set — "
                    "running UNAUTHENTICATED (local dev mode only; never "
                    "expose this).")
    if not app_host:
        log.warning("APP_HOST not set — Host/Origin pinning disabled "
                    "(local dev mode only).")

    manager = JobManager(data_dir, runner=runner)
    manager.recover()
    if start_worker:
        manager.start()
    app.extensions["tastetwin_jobs"] = manager

    @app.template_filter("datetime")
    def _fmt_datetime(ts) -> str:
        try:
            return datetime.fromtimestamp(float(ts)).strftime("%Y-%m-%d %H:%M")
        except (TypeError, ValueError, OSError, OverflowError):
            return "—"

    # -- middleware -----------------------------------------------------------

    @app.before_request
    def _cloudflare_access():  # fail closed on every route but /healthz
        if verifier is None or request.path == "/healthz":
            return None
        token = (request.headers.get("Cf-Access-Jwt-Assertion")
                 or request.cookies.get("CF_Authorization", ""))
        try:
            g.access_claims = verifier.verify(token)
        except AccessAuthError as exc:
            log.warning("rejected request to %s: %s", request.path, exc)
            abort(403)
        return None

    @app.before_request
    def _host_origin_pin():
        if not app_host or request.path == "/healthz":
            return None
        if request.host.split(":", 1)[0].lower() != app_host:
            abort(403)
        if request.method == "POST":
            origin = request.headers.get("Origin", "")
            if origin and (urlsplit(origin).hostname or "").lower() \
                    != app_host:
                abort(403)
        return None

    @app.after_request
    def _security_headers(resp: Response) -> Response:
        resp.headers.setdefault("X-Content-Type-Options", "nosniff")
        resp.headers.setdefault("X-Frame-Options", "DENY")
        resp.headers.setdefault("Referrer-Policy", "no-referrer")
        resp.headers.setdefault("Content-Security-Policy", _CSP)
        return resp

    # -- routes -----------------------------------------------------------------

    @app.get("/healthz")
    def healthz():
        return {"status": "ok"}

    @app.get("/")
    def index():
        return render_template("index.html", runs=manager.list_runs(),
                               pool_state=manager.pool_state,
                               max_len=MAX_USERNAME_LEN)

    @app.post("/run")
    def start_run():
        job, error = manager.enqueue(request.form.get("username", ""))
        if job is None:
            return render_template("index.html", runs=manager.list_runs(),
                                   pool_state=manager.pool_state,
                                   max_len=MAX_USERNAME_LEN,
                                   error=error), 400
        return redirect(url_for("run_status", username=job.username))

    @app.get("/run/<username>")
    def run_status(username: str):
        if not is_valid_name(username) or len(username) > MAX_USERNAME_LEN:
            abort(404)
        key = safe_filename(username.lower())
        job = manager.get(key)
        report_exists = (
            data_dir / "runs" / key / "report.html").exists()
        if job is None and not report_exists:
            abort(404)
        return render_template(
            "status.html", job=job, username=username,
            position=manager.position(key),
            log_lines=manager.log_tail(key),
            report_exists=report_exists,
            pool_state=manager.pool_state,
            refresh=job is not None and job.status in ("queued", "running"))

    @app.get("/report/<username>")
    def report(username: str):
        if not is_valid_name(username) or len(username) > MAX_USERNAME_LEN:
            abort(404)
        runs_root = (data_dir / "runs").resolve()
        path = (runs_root / safe_filename(username.lower())
                / "report.html").resolve()
        # is_valid_name + safe_filename already forbid traversal; this
        # containment check is belt-and-braces.
        if not path.is_relative_to(runs_root) or not path.is_file():
            abort(404)
        resp = send_file(path, mimetype="text/html")
        resp.headers["Content-Disposition"] = "inline"
        return resp

    @app.get("/about")
    def about():
        return render_template("about.html", methodology=METHODOLOGY)

    return app
